# Variables

A variable is a name used to store data 

(Remember: The term 'data' is plural, whereas a datum is a single value). 

This could be any type of data, dataframe etc. but here we will consider numerical  values. 

You can allocate a number to a variable name by using the equals sign.

How would you allocate the value twelve to the letter a?

In [1]:
# Example

a = 12
a

12

You can also allocate multiple values to multiple variables at once. 

So for example, you can use a comma to separate the variable names and the values. 

In [2]:
b, c = 67.2, 3.14
print(b, c)

67.2 3.14


So remember, the equals sign ("=") is the **assignment operator**. In the first example, we assign *12* to the variable *a*. In the second case, we assign a value of 67.2 to *b* and a value of 3.14 to *c*.

More specifically, the variable name (such as *a*) is associated with a memory location in your computer (that's what's happening under the hood!). 

<div class="alert alert-block alert-info">
    
<b>Note:</b> Python stores the *numerical value* and not the expression used to generate it. Therefore, in the first cell, 12 is stored and not *a*. In fact, they are stored as binary numbers (0s and 1s) 

</div>

The following examples demonstrate the concept.

In [3]:
a = 23

In [4]:
b = a

In [5]:
a

23

In [6]:
b

23

In [7]:
a = 13

In [8]:
a

13

In [9]:
b

23

<div class="alert alert-block alert-info">
    
<b>Note:</b> The assignment variable works from right to left; i.e it assigns the value of the number on the right to the variable name on the left. 
Therefore, the statement "6 = a" does not make sense. 

The assignment operator is not equivalent to the equals sign in algebra. 
</div>

The assigment operator can be used to increment, decrease or generally change the value of a variable.

In [10]:
a = 3

In [11]:
a = a + 1

In [12]:
a

4

In algebra, a = a + 1 is not logical. However, in python, it implies that we "add 1" to the current value of *a* and assign the results to *a*. 

This is a common operation in most programming languages using operations such as +=, -=, /= and *=. 

Remember, you can see more here: https://www.w3schools.com/python/python_operators.asp

In [14]:
e, f = 5, 9.8

In [15]:
e += 2

In [16]:
e, f

(7, 9.8)

In [17]:
e *= 3

In [18]:
e

21

In [138]:
f /= -2

In [139]:
f

-4.9

In [140]:
f -= 4

In [141]:
f

-8.9

#### Legal and recommended variable names

Make sure you are aware that python has it's own style guide, known as the PEP 8 -- Style Guide for Python Code

See here: https://www.python.org/dev/peps/pep-0008/

Also be aware:

1. Variable names must start with a letter but can then be followed by alphanumeric characters.
2. Spaces are not allowed, instead you can use, for example, an underscore character "_".
3. It is advisable to write variable names in small case since python is case sensitive.
4. It is recommended that variable names should be descriptive as in following examples. 

In [13]:
# Examples:
speed_of_light = 3.0*10**8 #variable to store speed of light
frequency_of_GPS_satellite = 1575.42*10**6 #variable to store frequency
wavelength = speed_of_light/frequency_of_GPS_satellite #calculate the wavelength from above variables
speed_of_light, frequency_of_GPS_satellite, wavelength

(300000000.0, 1575420000.0, 0.19042541036675933)

Remember: Anything written to the right of the pound sign ('#') in an active Python cell is commented out.

And thus not run by the console! 

Adding comments to code is really important as it helps you remember why you did certain things. 

#### Reserved words 

Some words and names are reserved by Python for special functions and purposes and must be avoided.

In python, such words should automatically change color to green, purple or any other color depending on the editor one is using. 

Examples of such words include and, as, assert, break, class, continue, def, del, elif, else, except,exec, finally, for, from, global, if, import, in, is, lambda, not, or, pass, print, raise, return, try, while, with, yield*

Examine the color of the reserved words below in this simple loop:

In [143]:
for my_iterator in range(0,3):
    print(i)

0
1
2


# Exercise


The distance to DC from GMU Fairfax campus is ~20 miles. 

Create a variable called `distance_miles` and allocate the value 20:

In [144]:
#Enter your attempt below:


One mile equates to approximately 1.6 kilometers.

Create a variable called `miles_to_kilometers` and allocate the value 1.6.

In [145]:
#Enter your attempt below:


Now divide the `distance_miles` variable by the `miles_to_kilometers` variable, to get the estimated distance in metric kilometers. Make sure you use the variable names, not the values provided.

Print the result to the console:

In [146]:
#Enter your attempt below:


You decide to stop off at Chantilly, VA, on your way, which means your return trip to DC is now an extra ~10 miles longer.

Add an extra 10 miles to the `distance_miles` variable, and print the result to the console. 

In [147]:
#Enter your attempt below:


Now convert this distance to metric kilometers, using the `miles_to_kilometers` variable.

Print the result to the console:

In [148]:
#Enter your attempt below:
